apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
  namespace: bggns
spec:
  type: NodePort
  selector:
    name: bggapp-po
  ports:
  - port: 3000
    targetPort: 3000