apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  labels:
    name: bggdb-svc
  namespace: bggns
spec:
  type: ClusterIP
  selector:
    name: bggdb-po
  ports:
  - port: 3306
    targetPort: 3306