# Create secret
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  labels:
    name: minio-secret
    app: minio
  namespace: minio
type: Opaque
data:
  # admin
  MINIO_ROOT_USER: YWRtaW4=
  # lkfd92nlk329fds
  MINIO_ROOT_PASSWORD: bGtmZDkybmxrMzI5ZmRz